server:
  port: 9090

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


zuul:
  prefix: /api
  routes:
    auth:
      path: /security/**
      serviceId: auth-service
      sensitive-headers: Cookie,Set-Cookie
    users:
      path: /users/**
      serviceId: users-service
    contacts:
      path: /contact/**
      serviceId: contact-service
    binaries:
      path: /binaries/**
      serviceId: binaries-service
    sales:
      path: /sales/**
      serviceId: sales-service

security:
  jwt:
    uri: /api/security/**
